source 'https://rubygems.org'

gem 'elasticsearch-transport', '7.5.0'
gem 'fluent-plugin-elasticsearch', '2.8.6'
gem 'fluent-plugin-rewrite-tag-filter', '2.2.0'
gem 'fluent-plugin-grep', '0.3.4'
gem 'fluent-plugin-parser', '0.4.1'
gem 'fluent-plugin-grok-parser', '2.6.1'
gem 'fluent-plugin-detect-exceptions', '0.0.13'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluentd', [">= 0.14.2", "<= 1.7.4"]

#gem 'fluent-plugin-systemd', '~>0.3.1'

