actions:
  1:
    action: delete_indices
    description: >-
       Delete indices for logstash-prefixed indices:
       - older than ${UNIT_COUNT:1} ${UNIT:months} (based on index name)
       Ignore the error if the filter does not result in an
       actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: fluentd-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: ${UNIT:months}
      unit_count: ${UNIT_COUNT:1}
      exclude:
  2:
    action: delete_indices
    description: >-
       Delete indices for logstash-prefixed indices:
       - greater than ${DISK_SPACE:20} (based on disk disk consumption)
       Ignore the error if the filter does not result in an
       actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: fluentd-
      exclude:
    - filtertype: space
      disk_space: ${DISK_SPACE:20}
      source: creation_date
      timestring: '%Y.%m.%d'
      exclude:
